from math import sin, cos, pi, tau, sqrt

PI = pi
TAU = tau
PHI = (1 + sqrt(5)) / 2.0
FINE_STRUCTURE_CONST = 360.0 - (360.0 / PHI)
EARTH_TILT = (360.0 / PHI) / 10.0
EARTH_IN_LUNAR_DIAMETERS = 108.0
EARTH_IN_SOLAR_DIAMETERS = 108.0
EARTH_AND_MOON_DIAMETER = 10080.0
EARTH_RADIUS = 3960.0
EARTH_CIRCUM = 21600.0
MOON_DIAMETER = 2160.0
MOON_RADIUS = 1080.0
SUN_DIAMETER = 864000.0

SEC = 60.0
MINUTE = 60.0
HOUR = SEC*MINUTE
WEEK = 7.0
DAY = 24.0
YEAR = 12.0
MONTH = 30.0
GREAT_YEAR = MOON_DIAMETER * YEAR

DAYS_IN_YEAR = MONTH * YEAR
DAYS_IN_GREAT_YEAR = DAYS_IN_YEAR * GREAT_YEAR
HOURS_IN_YEAR = DAY * DAYS_IN_YEAR
HOURS_IN_GREAT_YEAR = HOURS_IN_YEAR * GREAT_YEAR
MINUTES_IN_GREAT_YEAR = HOURS_IN_GREAT_YEAR * 60.0
SECS_IN_GREAT_YEAR = MINUTES_IN_GREAT_YEAR * 60.0
SECS_IN_DAY = HOUR * DAY
SECS_IN_YEAR = SECS_IN_DAY * YEAR

PRECESSION_ANGLE_YEAR = TAU / GREAT_YEAR
PRECESSION_ANGLE_DAY = TAU / DAYS_IN_GREAT_YEAR
PRECESSION_ANGLE_MONTH = PRECESSION_ANGLE_DAY * MONTH
PRECESSION_ANGLE_HOUR = TAU / HOURS_IN_GREAT_YEAR
PRECESSION_ANGLE_MINUTE = TAU / MINUTES_IN_GREAT_YEAR
PRECESSION_ANGLE_SEC = TAU / SECS_IN_GREAT_YEAR
SPIN_ANGLE_SEC = TAU / SECS_IN_DAY
MIN_VAL = 1e-13















def golden_ratio_division(whole): return whole/PHI,whole-(whole/PHI)

print(HOURS_IN_GREAT_YEAR,MINUTES_IN_GREAT_YEAR,SECS_IN_GREAT_YEAR)
print(PRECESSION_ANGLE_DAY,PRECESSION_ANGLE_HOUR,PRECESSION_ANGLE_MINUTE,PRECESSION_ANGLE_SEC)
print(SECS_IN_YEAR)

